#!/bin/bash

boxSize=1
width=$(mediainfo "$1" | grep Width | sed 's/ //g; s/[[:alpha:]]//g; s/://g')
outName=$(basename "${1%.*}")

function index() {
    echo "<link href='./${outName}.css' rel='stylesheet'>"
    printf "<body>\n<div class='row'>\n"
    sed -E 's|#(..)(..)(..)|    <div class="color\1\2\3"></div>|' |
        awk -v h="$width" '1;!(NR%h) {print "</div>\n<div class=\"row\">\n"}'
    printf "</body>\n"
}

function style() {
    rowClass=".row {display: flex; flex-direction: row;}"
    pixelClass=".row > div {width: ${boxSize}px; height:${boxSize}px;}"
    printf "%s\n%s\n" "$rowClass" "$pixelClass"
    sort -u | sed -E 's/#(..)(..)(..)/.color\1\2\3 {background-color: #\1\2\3;}/g'
}

convert "$1" txt: | grep -o '#[A-F0-9]\{6\}' | tee >(index > "$outName".html) >(style > "$outName".css) >/dev/null
